In [2]:
import numpy as np

In [3]:

l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional numpy array: ",a)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array:  [  12.23   13.32  100.     36.32]


In [4]:
x = np.zeros(10)
print(x)
print("11 en posicion 6")
x[6] = 11
print(x)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
11 en posicion 6
[  0.   0.   0.   0.   0.   0.  11.   0.   0.   0.]


In [5]:
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37]


In [6]:
x = np.arange(12, 38)
print("array original:")
print(x)
print("reversa:")
x = x[::-1]
print(x)

array original:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37]
reversa:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13
 12]


In [7]:
x = np.ones((5,5))
print("Array original:")
print(x)
print("1 en el borde")
x[1:-1,1:-1] = 0
print(x)

Array original:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
1 en el borde
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [8]:
x = np.ones((3,3))
print("array original:")
print(x)
print("0 en el borde")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

array original:
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
0 en el borde
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]


In [9]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [10]:
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("valores en grados Fahrenheit:")
print(F)
print("valores en grados centigrados:") 
print(5*F/9 - 5*32/9)

valores en grados Fahrenheit:
[  0.    12.    45.21  34.    99.91]
valores en grados centigrados:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [11]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("valores en array1 que no estan en array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
valores en array1 que no estan en array2:
[ 0 20 60 80]


In [12]:
p =  np.diagflat([4, 5, 6, 8])
print(p)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
